const movies = [
  {name: 'Eraserhead', releaseDate: 1997, director: 'David Lynch'},
  {name: 'Mulholland Drive', releaseDate: 2001, director: 'David Lynch'},
  {name: '2001: A Space Odyssey', releaseDate: 1968, director: 'Stanley Kubrick'},
  {name: 'Eyes Wide Shut', releaseDate: 1999, director: 'Stanley Kubrick'},
  {name: 'Four Nights of a Dreamer', releaseDate: 1971, director: 'Robert Bresson'},
  {name: 'The Devil, Probably', releaseDate: 1977, director: 'Robert Bresson'},
  {name: 'Psycho', releaseDate: 1960, director: 'Alfred Hitchcock'},
  {name: 'Vertigo', releaseDate: 1958, director: 'Alfred Hitchcock'},
  {name: 'Goodfellas', releaseDate: 1990, director: 'Martin Scorsese'},
  {name: 'The Departed', releaseDate: 2006, director: 'Martin Scorsese'},
  {name: 'Million Dollar Baby', releaseDate: 2004, director: 'Clint Eastwood'},
  {name: 'American Sniper', releaseDate: 2014, director: 'Clint Eastwood'},
  {name: 'Roman Holiday', releaseDate: 1953, director: 'William Wyler'},
  {name: 'Funny Girl', releaseDate: 1968, director: 'William Wyler'},
  {name: 'Sabrina', releaseDate: 1954, director: 'Billy Wilder'},
  {name: 'Some Like It Hot', releaseDate: 1959, director: 'Billy Wilder'},
  {name: 'The Quiet Man', releaseDate: 1952, director: 'John Ford'},
  {name: 'The Last Hurrah', releaseDate: 1958, director: 'John Ford'},
  {name: 'Woman in the Moon', releaseDate: 1929, director: 'Fritz Lang'},
  {name: 'Journey to the Lost City', releaseDate: 1960, director: 'Fritz Lang'},
  {name: 'Eyes in the Night', releaseDate: 1942, director: 'Fred Zinnemann'},
  {name: 'A Man for All Seasons', releaseDate: 1966, director: 'Fred Zinnemann'},
  {name: 'The Wiz', releaseDate: 1978, director: 'Sidney Lumet'},
  {name: 'Guilty as Sin', releaseDate: 1993, director: 'Sidney Lumet'},
  {name: 'The Godfather', releaseDate: 1972, director: 'Francis Ford Coppola'},
  {name: 'Apocalypse Now', releaseDate: 1979, director: 'Francis Ford Coppola'},
  {name: 'Se7en', releaseDate: 1995, director: 'David Fincher'},
  {name: 'The Social Network', releaseDate: 2010, director: 'David Fincher'},
  {name: 'Marriage Italian Style', releaseDate: 1964, director: 'Vittorio De Sica'},
  {name: 'A Place for Lovers', releaseDate: 1968, director: 'Vittorio De Sica'},
  {name: 'The Good, the Bad and the Ugly', releaseDate: 1966, director: 'Sergio Leone'},
  {name: 'Once Upon a Time in America', releaseDate: 1984, director: 'Sergio Leone'},
  {name: 'La Dolce Vita', releaseDate: 1960, director: 'Federico Fellini'},
  {name: 'Roma', releaseDate: 1972, director: 'Federico Fellini'},
  {name: 'All These Women', releaseDate: 1964, director: 'Ingmar Bergman'},
  {name: 'Shame', releaseDate: 1968, director: 'Ingmar Bergman'},
  {name: 'A Streetcar Named Desire', releaseDate: 1951, director: 'Elia Kazan'},
  {name: 'Wild River', releaseDate: 1960, director: 'Elia Kazan'},
  {name: 'Beat the Devil', releaseDate: 1953, director: 'John Huston'},
  {name: 'The Man Who Would Be King', releaseDate: 1975, director: 'John Huston'},
  {name: 'Alexander the Great', releaseDate: 1980, director: 'Theodoros Angelopoulos'},
  {name: 'The Dust of Time', releaseDate: 2008, director: 'Theodoros Angelopoulos'},
  {name: 'Seven Samurai', releaseDate: 1954, director: 'Akira Kurosawa'},
  {name: 'Throne of Blood', releaseDate: 1957, director: 'Akira Kurosawa'},
  {name: 'Chungking Express', releaseDate: 1994, director: 'Kar-Wai Wong'},
  {name: 'In the Mood for Love', releaseDate: 2000, director: 'Kar-Wai Wong'},
  {name: 'Hero', releaseDate: 2002, director: 'Yimou Zhang'},
  {name: 'Shadow', releaseDate: 2018, director: 'Yimou Zhang'},
  {name: 'My Neighbor Totoro', releaseDate: 1988, director: 'Hayao Miyazaki'},
  {name: 'Spirited Away', releaseDate: 2001, director: 'Hayao Miyazaki'},
  {name: 'Temptress Moon', releaseDate: 1996, director: 'Kaige Chen'},
  {name: 'Caught in the Web', releaseDate: 2012, director: 'Kaige Chen'},
  {name: 'Les Enfants Terribles', releaseDate: 1950, director: 'Jean-Pierre Melville'},
  {name: 'Army of Shadows', releaseDate: 1969, director: 'Jean-Pierre Melville'},
  {name: 'The Promise', releaseDate: 1996, director: 'Jean-Pierre Dardenne'},
  {name: 'The Kid with a Bike', releaseDate: 2011, director: 'Jean-Pierre Dardenne'},
  {name: 'Delicatessen', releaseDate: 1991, director: 'Jean-Pierre Jeunet'},
  {name: 'Amélie', releaseDate: 2001, director: 'Jean-Pierre Jeunet'},
  {name: 'A Woman Is a Woman', releaseDate: 1961, director: 'Jean-Luc Godard'},
  {name: 'Goodbye to Language', releaseDate: 2014, director: 'Jean-Luc Godard'},
  {name: 'The Immigrant', releaseDate: 1917, director: 'Charles Chaplin'},
  {name: 'The Great Dictator', releaseDate: 1940, director: 'Charles Chaplin'},
  {name: 'Our Hospitality', releaseDate: 1923, director: 'Buster Keaton'},
  {name: 'The General', releaseDate: 1926, director: 'Buster Keaton'},
  {name: 'The Steamroller and the Violin', releaseDate: 1961, director: 'Andrei Tarkovsky'},
  {name: 'Stalker', releaseDate: 1979, director: 'Andrei Tarkovsky'},
  {name: 'Straw Dogs', releaseDate: 1971, director: 'Sam Peckinpah'},
  {name: 'Convoy', releaseDate: 1978, director: 'Sam Peckinpah'},
  {name: 'Aliens', releaseDate: 1986, director: 'James Cameron'},
  {name: 'Titanic', releaseDate: 1997, director: 'James Cameron'},
  {name: 'Truly Madly Deeply', releaseDate: 1990, director: 'Anthony Minghella'},
  {name: 'The Talented Mr. Ripley', releaseDate: 1999, director: 'Anthony Minghella'},
  {name: 'So This Is Love', releaseDate: 1928, director: 'Frank Capra'},
  {name: 'State of the Union', releaseDate: 1948, director: 'Frank Capra'},
  {name: 'Citizen Kane', releaseDate: 1941, director: 'Orson Welles'},
  {name: 'Touch of Evil', releaseDate: 1958, director: 'Orson Welles'},
  {name: 'Beetlejuice', releaseDate: 1988, director: 'Tim Burton'},
  {name: 'Planet of the Apes', releaseDate: 2001, director: 'Tim Burton'},
  {name: 'Mystery Train', releaseDate: 1989, director: 'Jim Jarmusch'},
  {name: 'Coffee and Cigarettes', releaseDate: 2003, director: 'Jim Jarmusch'},
  {name: 'Knife in the Water', releaseDate: 1962, director: 'Roman Polanski'},
  {name: 'The Pianist', releaseDate: 2002, director: 'Roman Polanski'},
  {name: 'Last Tango in Paris', releaseDate: 1972, director: 'Bernardo Bertolucci'},
  {name: 'The Dreamers', releaseDate: 2003, director: 'Bernardo Bertolucci'},
  {name: 'The Scar', releaseDate: 1976, director: 'Krzysztof Kieslowski'},
  {name: 'Three Colors: Blue', releaseDate: 1993, director: 'Krzysztof Kieslowski'},
  {name: 'American Beauty', releaseDate: 1999, director: 'Sam Mendes'},
  {name: 'Skyfall', releaseDate: 2012, director: 'Sam Mendes'},
  {name: 'Heat', releaseDate: 1995, director: 'Michael Mann'},
  {name: 'Public Enemies', releaseDate: 2009, director: 'Michael Mann'},
  {name: 'Splash', releaseDate: 1984, director: 'Ron Howard'},
  {name: 'A Beautiful Mind', releaseDate: 2001, director: 'Ron Howard'},
  {name: 'To Die For', releaseDate: 1995, director: 'Gus Van Sant'},
  {name: 'Milk', releaseDate: 2008, director: 'Gus Van Sant'},
  {name: 'Boogie Nights', releaseDate: 1997, director: 'Paul Thomas Anderson'},
  {name: 'Punch-Drunk Love', releaseDate: 2002, director: 'Paul Thomas Anderson'},
  {name: 'The Royal Tenenbaums', releaseDate: 2001, director: 'Wes Anderson'},
  {name: 'The Grand Budapest Hotel', releaseDate: 2014, director: 'Wes Anderson'},
  {name: 'The Shawshank Redemption', releaseDate: 1994, director: 'Frank Darabont'},
  {name: 'The Green Mile', releaseDate: 1999, director: 'Frank Darabont'},
  {name: 'Raiders of the Lost Ark', releaseDate: 1981, director: 'Steven Spielberg'},
  {name: 'E.T. the Extra-Terrestrial', releaseDate: 1982, director: 'Steven Spielberg'},
  {name: 'Manhattan', releaseDate: 1979, director: 'Woody Allen'},
  {name: 'Vicky Cristina Barcelona', releaseDate: 2008, director: 'Woody Allen'},
  {name: 'Reservoir Dogs', releaseDate: 1992, director: 'Quentin Tarantino'},
  {name: 'The Hateful Eight', releaseDate: 2015, director: 'Quentin Tarantino'},
  {name: 'Desperado', releaseDate: 1995, director: 'Robert Rodriguez'},
  {name: 'Spy Kids', releaseDate: 2001, director: 'Robert Rodriguez'},
  {name: 'Matador', releaseDate: 1986, director: 'Pedro Almodóvar'},
  {name: 'Tie Me Up! Tie Me Down!', releaseDate: 1989, director: 'Pedro Almodóvar'},
  {name: 'Amores Perros', releaseDate: 2000, director: 'Alejandro G. Iñárritu'},
  {name: 'The Revenant', releaseDate: 2015, director: 'Alejandro G. Iñárritu'},
  {name: 'Great Expectations', releaseDate: 1998, director: 'Alfonso Cuarón'},
  {name: 'Gravity', releaseDate: 2013, director: 'Alfonso Cuarón'},
  {name: 'The Lord of the Rings: The Fellowship of the Ring', releaseDate: 2001, director: 'Peter Jackson'},
  {name: 'King Kong', releaseDate: 2005, director: 'Peter Jackson'},
  {name: 'Young Frankenstein', releaseDate: 1974, director: 'Mel Brooks'},
  {name: 'Spaceballs', releaseDate: 1987, director: 'Mel Brooks'},
  {name: 'Battle Circus', releaseDate: 1953, director: 'Richard Brooks'},
  {name: 'The Professionals', releaseDate: 1966, director: 'Richard Brooks'},
  {name: 'Paid to Love', releaseDate: 1927, director: 'Howard Hawks'},
  {name: 'Red River', releaseDate: 1948, director: 'Howard Hawks'},
  {name: 'The Pink Panther', releaseDate: 1963, director: 'Blake Edwards'},
  {name: 'The Tamarind Seed', releaseDate: 1974, director: 'Blake Edwards'},
  {name: 'Alexander the Great', releaseDate: 1956, director: 'Robert Rossen'},
  {name: 'The Hustler', releaseDate: 1961, director: 'Robert Rossen'},
  {name: 'When Father Was Away on Business', releaseDate: 1985, director: 'Emir Kusturica'},
  {name: 'Life Is a Miracle', releaseDate: 2004, director: 'Emir Kusturica'},
  {name: 'Cinema Paradiso', releaseDate: 1988, director: 'Giuseppe Tornatore'},
  {name: 'The Unknown Woman', releaseDate: 2006, director: 'Giuseppe Tornatore'},
  {name: 'Funny Games', releaseDate: 1997, director: 'Michael Haneke'},
  {name: 'Amour', releaseDate: 2012, director: 'Michael Haneke'},
  {name: 'Run Lola Run', releaseDate: 1998, director: 'Tom Tykwer'},
  {name: 'Cloud Atlas', releaseDate: 2012, director: 'Tom Tykwer'},
  {name: 'Batman Begins', releaseDate: 2005, director: 'Christopher Nolan'},
  {name: 'Inception', releaseDate: 2010, director: 'Christopher Nolan'},
  {name: 'The Dead Zone', releaseDate: 1983, director: 'David Cronenberg'},
  {name: 'A Dangerous Method', releaseDate: 2011, director: 'David Cronenberg'},
  {name: 'Fargo', releaseDate: 1996, director: 'Joel Coen'},
  {name: 'The Big Lebowski', releaseDate: 1998, director: 'Joel Coen'},
  {name: 'Sex, Lies, and Videotape', releaseDate: 1989, director: 'Steven Soderbergh'},
  {name: 'Magic Mike', releaseDate: 2012, director: 'Steven Soderbergh'},
  {name: 'Melancholia', releaseDate: 2011, director: 'Lars von Trier'},
  {name: 'The House That Jack Built', releaseDate: 2018, director: 'Lars von Trier'},
  {name: 'The 400 Blows', releaseDate: 1959, director: 'François Truffaut'},
  {name: 'The Man Who Loved Women', releaseDate: 1977, director: 'François Truffaut'},
  {name: 'Un Chien Andalou', releaseDate: 1929, director: 'Luis Buñuel'},
  {name: 'A Woman Without Love', releaseDate: 1952, director: 'Luis Buñuel'},
  {name: 'The Lady Without Camelias', releaseDate: 1953, director: 'Michelangelo Antonioni'},
  {name: 'Red Desert', releaseDate: 1964, director: 'Michelangelo Antonioni'},
  {name: 'Tootsie', releaseDate: 1982, director: 'Sydney Pollack'},
  {name: 'The Firm', releaseDate: 1993, director: 'Sydney Pollack'},
  {name: 'The Graduate', releaseDate: 1967, director: 'Mike Nichols'},
  {name: 'Regarding Henry', releaseDate: 1991, director: 'Mike Nichols'},
  {name: 'Her', releaseDate: 2013, director: 'Spike Jonze'},
  {name: 'Adaptation.', releaseDate: 2002, director: 'Spike Jonze'},
  {name: 'My Left Foot', releaseDate: 1989, director: 'Jim Sheridan'},
  {name: 'Get Rich or Die Tryin', releaseDate: 2005, director: 'Jim Sheridan'},
  {name: 'Casablanca', releaseDate: 1942, director: 'Michael Curtiz'},
  {name: 'White Christmas', releaseDate: 1954, director: 'Michael Curtiz'},
  {name: 'Lawrence of Arabia', releaseDate: 1962, director: 'David Lean'},
  {name: 'A Passage to India', releaseDate: 1984, director: 'David Lean'},
  {name: 'American Gangster', releaseDate: 2007, director: 'Ridley Scott'},
  {name: 'The Martian', releaseDate: 2015, director: 'Ridley Scott'},
  {name: 'Brother', releaseDate: 2000, director: 'Takeshi Kitano'},
  {name: 'Outrage Coda', releaseDate: 2017, director: 'Takeshi Kitano'},
  {name: 'Christmas in July', releaseDate: 1940, director: 'Preston Sturges'},
  {name: 'Unfaithfully Yours', releaseDate: 1948, director: 'Preston Sturges'},
  {name: 'JFK', releaseDate: 1991, director: 'Oliver Stone'},
  {name: 'Savages', releaseDate: 2012, director: 'Oliver Stone'},
  {name: 'Taking Off', releaseDate: 1971, director: 'Milos Forman'},
  {name: 'Man on the Moon', releaseDate: 1999, director: 'Milos Forman'},
  {name: 'The Long Goodbye', releaseDate: 1973, director: 'Robert Altman'},
  {name: 'Gosford Park', releaseDate: 2001, director: 'Robert Altman'},
  {name: 'State of Siege', releaseDate: 1972, director: 'Costa-Gavras'},
  {name: 'Eden Is West', releaseDate: 2009, director: 'Costa-Gavras'},
  {name: 'Innocent Sorcerers', releaseDate: 1960, director: 'Andrzej Wajda'},
  {name: 'The Promised Land', releaseDate: 1975, director: 'Andrzej Wajda'},
  {name: 'Dusk to Dawn', releaseDate: 1922, director: 'King Vidor'},
  {name: 'Duel in the Sun', releaseDate: 1946, director: 'King Vidor'},
  {name: 'The Bride of Glomdal', releaseDate: 1926, director: 'Carl Theodor Dreyer'},
  {name: 'Ordet', releaseDate: 1955, director: 'Carl Theodor Dreyer'},
  {name: 'Evening - Night - Morning', releaseDate: 1920, director: 'F.W. Murnau'},
  {name: '4 Devils', releaseDate: 1928, director: 'F.W. Murnau'},
  {name: 'The Love Flower', releaseDate: 1920, director: 'D.W. Griffith},
  {name: 'The Birth of a Nation', releaseDate: 1915, director: 'D.W. Griffith'},
  {name: 'Madame Bovary', releaseDate: 1934, director: 'Jean Renoir'},
  {name: 'The Golden Coach', releaseDate: 1952, director: 'Jean Renoir'},
  {name: 'The Merchant of Four Seasons', releaseDate: 1972, director: 'Rainer Werner Fassbinder'},
  {name: 'In a Year with 13 Moons', releaseDate: 1978, director: 'Rainer Werner Fassbinder'},
  {name: 'Braveheart', releaseDate: 1995, director: 'Mel Gibson'},
  {name: 'Hacksaw Ridge', releaseDate: 2016, director: 'Mel Gibson'},
  {name: 'Signs of Life', releaseDate: 1968, director: 'Werner Herzog'},
  {name: 'The Wild Blue Yonder', releaseDate: 2005, director: 'Werner Herzog'},
  {name: 'The Wild Blue Yonder', releaseDate: 1976, director: 'Brian De Palma'},
  {name: 'Scarface', releaseDate: 1983, director: 'Brian De Palma'},
  {name: '12 Monkeys', releaseDate: 1995, director: 'Terry Gilliam'},
  {name: 'The Man Who Killed Don Quixote', releaseDate: 2018, director: 'Terry Gilliam'},
  {name: 'The White Balloon', releaseDate: 1995, director: 'Jafar Panahi'},
  {name: 'Closed Curtain', releaseDate: 2013, director: 'Jafar Panahi'},
]